### PR TITLE
Port over G203

### PR DESCRIPTION
**Pull request by ulziibay**
Port Port G301, G302, G306, which are the filesystem  permissons checks. Uses 0o600 as threshold.

### CODE REVIEW

**Comment by ulziibay** [comment]
@minusworld gosec uses 0700 for some of this and 0600 for others. I did not run this on platform, but would be trivial to do!

**Comment by minusworld** [comment]
https://dev.massive.ret2.co/triager/filter/963

**Comment by ulziibay** [comment]
@minusworld it is not too restrictive nor noisy based on 9 out of ~1300 repos have this check fired. Should we ship it as is?

**Comment by minusworld** [comment]
> @minusworld it is not too restrictive nor noisy based on 9 out of ~1300 repos have this check fired. Should we ship it as is?

sg! 👍

**Pull request merged**
